In [ ]:
#numpy practice session

In [2]:
import numpy as np

# creating an array using numpy

In [3]:
#1-d array
food=np.array(["pakora", "samosa", "raita"])
food

array(['pakora', 'samosa', 'raita'], dtype='<U6')

In [4]:
price=np.array([5,5,5])
food

array(['pakora', 'samosa', 'raita'], dtype='<U6')

In [5]:
type(price)

numpy.ndarray

In [6]:
type(food)

numpy.ndarray

In [7]:
len(food)

3

In [8]:
len(price)

3

In [9]:
price[0:]

array([5, 5, 5])

In [10]:
food[0:]

array(['pakora', 'samosa', 'raita'], dtype='<U6')

In [11]:
price.mean()

5.0

In [12]:
price.max()

5

In [13]:
price.min()

5

In [14]:
#zeros method
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros([6])

array([0., 0., 0., 0., 0., 0.])

In [16]:
#ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
#range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
#specify
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [19]:
#specific interval
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
np.arange(1,50,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [22]:
np.arange(0,50,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [23]:
np.arange(0,30,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [24]:
# specific line space
np.linspace(0, 10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [28]:
np.linspace(2, 8,num=4)

array([2., 4., 6., 8.])

In [29]:
np.linspace(2,10,5)

array([ 2.,  4.,  6.,  8., 10.])

In [30]:
#specific data type
np.ones(5,dtype=np.int64)

array([1, 1, 1, 1, 1], dtype=int64)

In [31]:
np.ones(5,dtype=np.float64)

array([1., 1., 1., 1., 1.])

In [32]:
a=np.array([10,12,15,2,4,6,100,320,0.5,10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [34]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [36]:
b=np.array([10.2,3.4,53.6,1.6])
b

array([10.2,  3.4, 53.6,  1.6])

In [41]:
c=np.concatenate((a,b))
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  10.2,   3.4,  53.6,   1.6])

In [42]:
c.sort
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  10.2,   3.4,  53.6,   1.6])

# 2-D arrays


In [44]:
a=([[1,2], [5,4]])
a

[[1, 2], [5, 4]]

In [45]:
b=([6,7],[7,8])
b

([6, 7], [7, 8])

In [46]:
c=np.concatenate((a, b), axis=0)
c

array([[1, 2],
       [5, 4],
       [6, 7],
       [7, 8]])

In [48]:
c.sort()
c

array([[1, 2],
       [4, 5],
       [6, 7],
       [7, 8]])

In [49]:
c=np.concatenate((a, b), axis=1)
c

array([[1, 2, 6, 7],
       [5, 4, 7, 8]])

In [51]:
c=np.concatenate((a, b), axis=1)
c

array([[1, 2, 6, 7],
       [5, 4, 7, 8]])

In [66]:
a=np.array([[[0,1,2,3],[4,5,6,7]],
            
            [[0,1,2,3],[4,5,6,7]],
            
           [[0,1,2,3],[4,5,6,7]]])
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [67]:
a.size

24

In [53]:
a.ndim

3

In [60]:
a.ndim

3

In [56]:
b=np.array([[5,6,7],
           [8,9,10],
           [10,11,12]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [10, 11, 12]])

In [57]:
b.ndim

2

In [58]:
type(b)

numpy.ndarray

In [68]:
a.size

24

In [69]:
a.shape

(3, 2, 4)

In [87]:
a=np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [88]:
a.shape

(9,)

In [77]:
b=a.reshape(2,4)
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [89]:
a=np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [90]:
b=a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [91]:
#reshape
np.reshape(a, newshape=(1, 9), order="c")

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [92]:
np.reshape(a, newshape=(1, 9), order="c")

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [96]:
# convert 1d into 2d
a=np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
#row wise 2d conversion
b=a[np.newaxis,:]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [98]:
b.shape

(1, 9)

In [99]:
#column wise 2d conversion
c=a[:, np.newaxis,]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [100]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
a[2:6]

array([3, 4, 5, 6])

In [103]:
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [104]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [105]:
b*2

array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18]])

In [106]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [107]:
a.sum()

45

In [108]:
a.mean()

5.0